name: Generate Pong Contribution Game

on:
  schedule:
    - cron: "0 0 * * *"   # every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pong SVG
        uses: Platane/snk@v3
        with:
          github_user_name: print-hasaesh
          outputs: |
            dist/pong.svg?palette=github-dark&color_snake=#00ffcc

      - name: Push SVG
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
